//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posuda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PosudaEntities : DbContext
    {
        public PosudaEntities()
            : base("name=PosudaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorySet> CategorySet { get; set; }
        public virtual DbSet<MakersSet> MakersSet { get; set; }
        public virtual DbSet<OrdersSet> OrdersSet { get; set; }
        public virtual DbSet<PointsSet> PointsSet { get; set; }
        public virtual DbSet<ProductsSet> ProductsSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
